#request (goal): servo deegrees to scan
float64 servo_start
float64 servo_end
int64 servo_waypoints
---
#result: all reads of the ultrasonic + each servo positivo for each read
float64[] ultrasonic_reads
float64[] servo_degrees
---
#constant feedback: actual ultrasonic read + actual servo position
float64 ultrasonic_read
float64 servo_degree